
import requests
import json
import time
from datetime import datetime

BASE_URL = "https://www.walmart.co.cr"
SEARCH_API = f"{BASE_URL}/api/catalog_system/pub/products/search"
CATEGORIAS = [
    "abarrotes",
  "abarrotes/aceites-de-cocina",
  "abarrotes/aceites-de-cocina/aceite-de-canola",
  "abarrotes/aceites-de-cocina/aceite-de-maiz",
  "abarrotes/aceites-de-cocina/aceite-de-oliva",
  "abarrotes/aceites-de-cocina/aceite-de-semillas-y-vegetal",
  "abarrotes/aceites-de-cocina/aceite-spray",
  "abarrotes/aceites-de-cocina/manteca",
  "abarrotes/aceites-de-cocina/manteca-vegetal",
  "abarrotes/alimentos-instantaneos",
  "abarrotes/alimentos-instantaneos/comida-rapida",
  "abarrotes/alimentos-instantaneos/cremas-instantaneas",
  "abarrotes/alimentos-instantaneos/pasta-y-sopa-instantanea",
  "abarrotes/alimentos-instantaneos/pure-instantaneo",
  "abarrotes/arroz-frijol-y-semillas",
  "abarrotes/arroz-frijol-y-semillas/arroz",
  "abarrotes/arroz-frijol-y-semillas/frijol",
  "abarrotes/arroz-frijol-y-semillas/leguminosas",
  "abarrotes/arroz-frijol-y-semillas/semillas",
  "abarrotes/azucar-y-postres",
  "abarrotes/azucar-y-postres/azucar",
  "abarrotes/azucar-y-postres/gelatinas-de-leche-en-polvo",
  "abarrotes/azucar-y-postres/gelatinas-y-flan",
  "abarrotes/azucar-y-postres/sustituto-de-azucar",
  "abarrotes/cafe-te-y-sustitutos",
  "abarrotes/cafe-te-y-sustitutos/cafe-en-grano",
  "abarrotes/cafe-te-y-sustitutos/cafe-listo-para-beber",
  "abarrotes/cafe-te-y-sustitutos/cafe-molido",
  "abarrotes/cafe-te-y-sustitutos/capsulas-de-cafe",
  "abarrotes/cafe-te-y-sustitutos/crema-para-cafe",
  "abarrotes/cafe-te-y-sustitutos/filtros-para-cafe",
  "abarrotes/cafe-te-y-sustitutos/te-medicinales",
  "abarrotes/cereales-y-barras",
  "abarrotes/cereales-y-barras/avena-y-granola",
  "abarrotes/cereales-y-barras/barras-de-cereal",
  "abarrotes/cereales-y-barras/cereal-dulce",
  "abarrotes/cereales-y-barras/de-fibra-y-light",
  "abarrotes/dulces-y-chocolates",
  "abarrotes/dulces-y-chocolates/bombones",
  "abarrotes/dulces-y-chocolates/caramelos",
  "abarrotes/dulces-y-chocolates/chicles",
  "abarrotes/dulces-y-chocolates/chocolates",
  "abarrotes/dulces-y-chocolates/gomitas",
  "abarrotes/dulces-y-chocolates/sin-azucar",
  "abarrotes/enlatados-y-conservas",
  "abarrotes/enlatados-y-conservas/aceitunas",
  "abarrotes/enlatados-y-conservas/atun-y-pescado",
  "abarrotes/enlatados-y-conservas/carnes-enlatadas",
  "abarrotes/enlatados-y-conservas/frijoles-instantaneos",
  "abarrotes/enlatados-y-conservas/frutas-en-almibar",
  "abarrotes/enlatados-y-conservas/mariscos-enlatados",
  "abarrotes/enlatados-y-conservas/sopas-y-cremas",
  "abarrotes/enlatados-y-conservas/vegetales-enlatados",
  "abarrotes/especiales-y-sazonadores",
  "abarrotes/especiales-y-sazonadores/consomes",
  "abarrotes/especiales-y-sazonadores/especias",
  "abarrotes/especiales-y-sazonadores/sal-y-condimentos",
  "abarrotes/especiales-y-sazonadores/sazonadores",
  "abarrotes/especias-y-sazonadores",
  "abarrotes/especias-y-sazonadores/consomes",
  "abarrotes/especias-y-sazonadores/especias",
  "abarrotes/especias-y-sazonadores/sal-y-condimentos",
  "abarrotes/especias-y-sazonadores/sazonadores",
  "abarrotes/galletas",
  "abarrotes/galletas/galletas",
  "abarrotes/galletas/galletas-de-avena-y-cereal",
  "abarrotes/galletas/galletas-dulces",
  "abarrotes/galletas/galletas-integrales",
  "abarrotes/galletas/galletas-saladas",
  "abarrotes/harinas-y-reposteria",
  "abarrotes/harinas-y-reposteria/chocolates-para-reposteria",
  "abarrotes/harinas-y-reposteria/de-arroz",
  "abarrotes/harinas-y-reposteria/harina-de-trigo-y-maiz",
  "abarrotes/harinas-y-reposteria/para-hot-cakes",
  "abarrotes/harinas-y-reposteria/reposteria",
  "abarrotes/harinas-y-reposteria/saborizantes-artificiales",
  "abarrotes/leche",
  "abarrotes/leche/condensada",
  "abarrotes/leche/en-polvo",
  "abarrotes/leche/evaporada",
  "abarrotes/leche/leche-deslactosada",
  "abarrotes/leche/leche-entera",
  "abarrotes/leche/leche-especializada",
  "abarrotes/leche/leche-light",
  "abarrotes/leche/leche-saborizada",
  "abarrotes/leche/leche-semi-y-descremada",
  "abarrotes/mermeladas-y-miel",
  "abarrotes/mermeladas-y-miel/cajeta-y-dulce-de-leche",
  "abarrotes/mermeladas-y-miel/crema-de-avellana-y-mantequilla-de-mani",
  "abarrotes/mermeladas-y-miel/mermelada",
  "abarrotes/mermeladas-y-miel/miel",
  "abarrotes/mermeladas-y-miel/otras-mieles",
  "abarrotes/pastas",
  "abarrotes/pastas/fetuccini",
  "abarrotes/pastas/fusilli",
  "abarrotes/pastas/pasta-especial",
  "abarrotes/pastas/pasta-precocida",
  "abarrotes/pastas/salsa-para-pasta-y-pizza",
  "abarrotes/pastas/spaghetti",
  "abarrotes/productos-vegetales-y-veganos",
  "abarrotes/productos-vegetales-y-veganos/alimentos-veganos",
  "abarrotes/salsa-aderezos-y-vinagre",
  "abarrotes/salsa-aderezos-y-vinagre/aderezos-y-vinagretas",
  "abarrotes/salsa-aderezos-y-vinagre/catsup-y-mostaza",
  "abarrotes/salsa-aderezos-y-vinagre/mayonesa",
  "abarrotes/salsa-aderezos-y-vinagre/salsa-de-soya-y-teriyaki",
  "abarrotes/salsa-aderezos-y-vinagre/salsa-picante",
  "abarrotes/salsa-aderezos-y-vinagre/salsas-caseras",
  "abarrotes/salsa-aderezos-y-vinagre/salsas-para-sazonar",
  "abarrotes/salsa-aderezos-y-vinagre/vinagre",
  "abarrotes/snacks-y-fruta-seca",
  "abarrotes/snacks-y-fruta-seca/chicharrones",
  "abarrotes/snacks-y-fruta-seca/dip",
  "abarrotes/snacks-y-fruta-seca/frutas-secas",
  "abarrotes/snacks-y-fruta-seca/mani-y-otras-semillas",
  "abarrotes/snacks-y-fruta-seca/mix-de-semillas",
  "abarrotes/snacks-y-fruta-seca/nueces-y-almendras",
  "abarrotes/snacks-y-fruta-seca/palomitas",
  "abarrotes/snacks-y-fruta-seca/papas-y-frituras",
  "abarrotes/snacks-y-fruta-seca/snacks",
  "alimentos-congelados",
  "alimentos-congelados/comida-facil",
  "alimentos-congelados/comida-facil/comida-congelada",
  "alimentos-congelados/comida-facil/comida-infantil",
  "alimentos-congelados/comida-facil/papas-congeladas",
  "alimentos-congelados/comida-facil/pescados-y-mariscos",
  "alimentos-congelados/comida-facil/pollo-preparado",
  "alimentos-congelados/comida-facil/tacos-pizzas-y-pastas",
  "alimentos-congelados/frutas-y-verdura-congelada",
  "alimentos-congelados/frutas-y-verdura-congelada/frutas-congeladas",
  "alimentos-congelados/frutas-y-verdura-congelada/verduras-congeladas",
  "alimentos-congelados/hielo",
  "alimentos-congelados/hielo-empacado",
  "alimentos-congelados/hielo/hielo",
  "alimentos-congelados/postres-congelados",
  "alimentos-congelados/postres-congelados/barquillos-y-conos",
  "alimentos-congelados/postres-congelados/helados",
  "alimentos-congelados/postres-congelados/hot-cakes-y-wafles",
  "alimentos-congelados/postres-congelados/pay-y-pasteles",
  "bebes-y-ninos/articulos-para-fiesta/envolturas-para-regalo",
  "bebes-y-ninos/articulos-para-fiesta/globos",
  "bebes-y-ninos/articulos-para-fiesta/invitaciones-y-tarjetas",
  "bebes-y-ninos/articulos-para-fiesta/velas-de-cumpleanos",
  "bebes-y-ninos/comida-para-bebe-y-lactancia",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/accesorios-de-lactancia",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/biberones-y-tetinas",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/cereales-y-galletas-para-bebe",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/colados-1ra-etapa",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/colados-2da-etapa",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/colados-3ra-etapa",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/colados-4ta-etapa-y-junior",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/formulas-lacteas",
  "bebes-y-ninos/comida-para-bebe-y-lactancia/platos-vasos-y-cubiertos-para-ninos",
  "bebes-y-ninos/cunas-coches-y-accesorios",
  "bebes-y-ninos/cunas-coches-y-accesorios/accesorios-para-bebes",
  "bebes-y-ninos/cunas-coches-y-accesorios/coches-asientos-de-auto-y-canguros",
  "bebes-y-ninos/cunas-coches-y-accesorios/cunas-y-encierros",
  "bebes-y-ninos/higiene-del-bebe",
  "bebes-y-ninos/higiene-del-bebe/accesorios-para-bano-de-bebes",
  "bebes-y-ninos/higiene-del-bebe/crema-gel-y-locion-para-bebe",
  "bebes-y-ninos/higiene-del-bebe/shampoo-y-jabon-para-bebe",
  "bebes-y-ninos/higiene-del-bebe/talco-y-aceite-para-bebe",
  "bebes-y-ninos/juguetes-para-bebe-y-estimulacion-temprana",
  "bebes-y-ninos/juguetes-para-bebe-y-estimulacion-temprana/juguetes-para-bebes",
  "bebes-y-ninos/juguetes-para-bebe-y-estimulacion-temprana/juguetes-preescolar",
  "bebes-y-ninos/panales-y-toallitas-humedas",
  "bebes-y-ninos/panales-y-toallitas-humedas/ecologicos-entrenadores-y-para-nadar",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-2",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-3",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-4",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-5",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-6",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales---etapa-7",
  "bebes-y-ninos/panales-y-toallitas-humedas/panales-recien-nacido-y-etapa-1",
  "bebes-y-ninos/panales-y-toallitas-humedas/toallitas-humedas",
  "deportes",
  "deportes/album-copa-america",
  "deportes/articulos-deportivos",
  "deportes/articulos-deportivos/accesorios-deportivos",
  "deportes/articulos-deportivos/balones-y-entrenamiento",
  "deportes/articulos-deportivos/campismo",
  "deportes/articulos-deportivos/entrenamiento-fisico",
  "deportes/articulos-deportivos/natacion",
  "deportes/articulos-deportivos/tenis-squash-y-boxeo",
  "electronica",
  "electronica/audio",
  "electronica/audio/accesorios-de-audio",
  "electronica/audio/audifonos",
  "electronica/audio/audio-para-vehiculos",
  "electronica/audio/barras-de-sonido-y-teatro-en-casa",
  "electronica/audio/sistemas-de-audio",
  "electronica/celulares",
  "electronica/celulares/accesorios-para-celular",
  "electronica/celulares/smartphones-y-celulares",
  "electronica/celulares/smartwatch-y-wearables",
  "electronica/computacion",
  "electronica/computacion/accesorios-de-computacion",
  "electronica/computacion/impresoras-multifuncionales-y-scanners",
  "electronica/computacion/ipad-y-tablet",
  "electronica/computacion/laptops",
  "electronica/electrodomesticos",
  "electronica/electrodomesticos/aires-acondicionados-y-ventiladores",
  "electronica/electrodomesticos/aspiradoras",
  "electronica/electrodomesticos/cafeteras-y-jarras-electricas",
  "electronica/electrodomesticos/dispensadores-de-agua",
  "electronica/electrodomesticos/extractores-y-procesadores-de-alimentos",
  "electronica/electrodomesticos/freidoras-y-ollas-electricas",
  "electronica/electrodomesticos/hornos-de-microondas-y-tostadores",
  "electronica/electrodomesticos/licuadoras-y-batidoras",
  "electronica/electrodomesticos/planchas-de-vapor",
  "electronica/electrodomesticos/sandwicheras-y-wafleras",
  "electronica/electrodomesticos/sartenes-electricos",
  "electronica/fotografia",
  "electronica/fotografia/camaras",
  "electronica/linea-blanca",
  "electronica/linea-blanca/cocinas-y-hornos",
  "electronica/linea-blanca/lava-vajillas-extractores",
  "electronica/linea-blanca/lavadoras-y-secadoras",
  "electronica/linea-blanca/refrigeradores-y-congeladores",
  "electronica/televisores",
  "electronica/televisores/accesorios-para-tv",
  "electronica/televisores/pantallas",
  "electronica/televisores/peliculas",
  "electronica/televisores/reproductores-dvd-y-blu-ray",
  "electronica/videojuegos",
  "electronica/videojuegos/accesorios-para-nintendo",
  "electronica/videojuegos/accesorios-para-pc",
  "electronica/videojuegos/accesorios-para-playstation",
  "electronica/videojuegos/accesorios-para-xbox",
  "electronica/videojuegos/consolas-nintendo",
  "electronica/videojuegos/consolas-playstation",
  "electronica/videojuegos/juegos-para-nintendo",
  "electronica/videojuegos/juegos-para-playstation",
  "electronica/videojuegos/otros---videojuegos",
  "electronica/videojuegos/otros-juegos-y-accesorios",
  "electronica/videojuegos/teclados-y-mouse",
  "farmacia",
  "farmacia/analgesicos",
  "farmacia/analgesicos/dolor",
  "farmacia/analgesicos/musculares-e-inflamacion",
  "farmacia/antibiotico",
  "farmacia/anticonceptivos-hormonal-y-salud-sexual",
  "farmacia/antimicotico",
  "farmacia/antiviral-gripe-y-tos",
  "farmacia/asma-alergias-y-nasal",
  "farmacia/bienestar-equipo-medico-y-soluciones-hospitalarias",
  "farmacia/bienestar-sexual",
  "farmacia/bienestar-sexual/condones",
  "farmacia/bienestar-sexual/lubricantes",
  "farmacia/bienestar-sexual/pruebas-de-embarazo",
  "farmacia/bienestar-sexual/suplementos",
  "farmacia/cardiovascular---hipertensivo",
  "farmacia/colesterol-y-triglicerido",
  "farmacia/cuidado-de-los-pies",
  "farmacia/cuidado-de-los-pies/accesorios",
  "farmacia/cuidado-de-los-pies/accesorios-cuidado-de-pies",
  "farmacia/cuidado-de-los-pies/antimicoticos-pies",
  "farmacia/cuidado-de-los-pies/antimicoticos-unas",
  "farmacia/cuidado-de-los-pies/callos-ampollas-y-juanetes",
  "farmacia/cuidado-de-los-pies/talcos",
  "farmacia/cuidado-personal",
  "farmacia/cuidado-personal/aceites-y-cremas",
  "farmacia/cuidado-personal/antiacne-px",
  "farmacia/cuidado-personal/cuidado-bucal",
  "farmacia/cuidado-personal/cuidado-de-la-piel",
  "farmacia/cuidado-personal/dermocosmeticos",
  "farmacia/cuidado-personal/higiene-femenina",
  "farmacia/cuidado-personal/masajeadores",
  "farmacia/cuidado-personal/para-cuidado-bucal",
  "farmacia/dermatologia",
  "farmacia/diabetes",
  "farmacia/diabetes-y-tiroides",
  "farmacia/diabetes/equipos-y-accesorios",
  "farmacia/diabetes/tratamiento-diabetes",
  "farmacia/dolor-e-inflamacion",
  "farmacia/embarazo---lactancia-infantil",
  "farmacia/equipo-medico",
  "farmacia/equipos-medicos",
  "farmacia/equipos-medicos/equipo-medico",
  "farmacia/estomacales",
  "farmacia/estomacales/antiacidos",
  "farmacia/estomacales/antidiarreicos",
  "farmacia/material-de-curacion",
  "farmacia/medicamentos-de-alta-especialidad",
  "farmacia/medicamentos-infantiles",
  "farmacia/medicamentos-infantiles/respiratorios",
  "farmacia/medicamentos-infantiles/vitamina-y-suplemento",
  "farmacia/multivitaminicos-suplementos---sistema-oseo",
  "farmacia/naturista-y-herbolarios",
  "farmacia/nutricion-deportiva",
  "farmacia/nutricion-deportiva/suplementos-deportivos",
  "farmacia/oftalmicos-y-oticos",
  "farmacia/oftalmicos-y-oticos/oidos",
  "farmacia/oftalmicos-y-oticos/soluciones-para-lentes",
  "farmacia/otc",
  "farmacia/respiratorios",
  "farmacia/respiratorios/alergias",
  "farmacia/respiratorios/congestion-nasal",
  "farmacia/respiratorios/garganta-irritada",
  "farmacia/respiratorios/resfrios",
  "farmacia/respiratorios/tos",
  "farmacia/salud-bucal-oftalmologico---oido",
  "farmacia/sistema-digestivo-y-antiparasitarios",
  "farmacia/sistema-nervioso",
  "farmacia/sistema-urinario",
  "farmacia/vacunas",
  "farmacia/vitaminas-y-suplementos",
  "farmacia/vitaminas-y-suplementos/calcio---embarazo",
  "farmacia/vitaminas-y-suplementos/multivitaminicos",
  "farmacia/vitaminas-y-suplementos/preventivos",
  "farmacia/vitaminas-y-suplementos/suplementos-nutricionales",
  "farmacia/vitaminas-y-suplementos/vitaminas",
  "frutas-y-verduras",
  "frutas-y-verduras/frutas",
  "frutas-y-verduras/frutas/bananos-papayas-y-tropicales",
  "frutas-y-verduras/frutas/fresa-frambuesa-y-moras",
  "frutas-y-verduras/frutas/frutas-de-temporada-y-exoticas",
  "frutas-y-verduras/frutas/manzanas-y-peras",
  "frutas-y-verduras/frutas/naranja-limon-y-citricos",
  "frutas-y-verduras/frutas/uvas-duraznos-y-ciruelas",
  "frutas-y-verduras/organicos",
  "frutas-y-verduras/organicos/verduras",
  "frutas-y-verduras/verduras",
  "frutas-y-verduras/verduras/calabazas-y-similares",
  "frutas-y-verduras/verduras/cebollas-papas-y-verduras-de-raiz",
  "frutas-y-verduras/verduras/chiles-ajos-y-pimientos",
  "frutas-y-verduras/verduras/ensaladas-y-empacados",
  "frutas-y-verduras/verduras/hongos-brocolis-y-esparragos",
  "frutas-y-verduras/verduras/lechugas-espinacas-y-hojas-verdes",
  "frutas-y-verduras/verduras/tomates-aguacates-y-basicos",
  "juguetes",
  "juguetes/jugueteria",
  "juguetes/jugueteria/bicicletas-patines-y-scooters",
  "juguetes/jugueteria/juegos-de-ciencia-y-creatividad",
  "juguetes/jugueteria/juegos-de-mesa",
  "juguetes/jugueteria/juegos-tradicionales",
  "juguetes/jugueteria/juguetes-de-agua-y-exterior",
  "juguetes/jugueteria/juguetes-de-construccion",
  "juguetes/jugueteria/juguetes-para-ninas",
  "juguetes/jugueteria/juguetes-para-ninos",
  "juguetes/jugueteria/peluches",
  "lacteos",
  "lacteos/crema-o-natilla",
  "lacteos/crema-o-natilla/regular",
  "lacteos/gelatinas-y-postres",
  "lacteos/gelatinas-y-postres/gelatinas",
  "lacteos/gelatinas-y-postres/postres",
  "lacteos/huevo",
  "lacteos/huevo/blanco",
  "lacteos/huevo/marron",
  "lacteos/huevo/pastoreo-y-especializado",
  "lacteos/leche",
  "lacteos/leche/condensada",
  "lacteos/leche/en-polvo",
  "lacteos/leche/evaporada",
  "lacteos/leche/leche-de-soya",
  "lacteos/leche/leche-deslactosada",
  "lacteos/leche/leche-entera",
  "lacteos/leche/leche-especializada",
  "lacteos/leche/leche-light",
  "lacteos/leche/leche-saborizada",
  "lacteos/leche/leche-semi-y-descremada",
  "lacteos/mantequillas-y-margarinas",
  "lacteos/mantequillas-y-margarinas/mantequillas",
  "lacteos/mantequillas-y-margarinas/margarinas",
  "lacteos/queso",
  "lacteos/queso-gourmet",
  "lacteos/queso-gourmet/mezcla-de-quesos-gourmet",
  "lacteos/queso-gourmet/queso-brie",
  "lacteos/queso-gourmet/queso-de-cabra",
  "lacteos/queso-gourmet/queso-edam",
  "lacteos/queso-gourmet/queso-jack",
  "lacteos/queso/mas-quesos",
  "lacteos/queso/queso-americano",
  "lacteos/queso/queso-cottage",
  "lacteos/queso/queso-crema",
  "lacteos/queso/queso-fresco",
  "lacteos/queso/queso-manchego",
  "lacteos/queso/queso-mozzarella",
  "lacteos/queso/queso-parmesano",
  "lacteos/yogurt",
  "lacteos/yogurt/yogurt-batido",
  "lacteos/yogurt/yogurt-bebible",
  "lacteos/yogurt/yogurt-natural",
  "limpieza",
  "limpieza/accesorios-para-limpieza",
  "limpieza/accesorios-para-limpieza/escobas-cepillos-y-escurridores-de-piso",
  "limpieza/accesorios-para-limpieza/fibras-y-esponjas",
  "limpieza/accesorios-para-limpieza/guantes",
  "limpieza/accesorios-para-limpieza/panos-y-franelas",
  "limpieza/accesorios-para-limpieza/prensas-de-ropa-y-tendederos",
  "limpieza/accesorios-para-limpieza/recogedores",
  "limpieza/accesorios-para-limpieza/tinas-y-cubetas",
  "limpieza/accesorios-para-limpieza/trapeadores-y-quitapelusas",
  "limpieza/aromatizantes",
  "limpieza/aromatizantes/aromatizante-ambiental",
  "limpieza/aromatizantes/aromatizante-de-bano",
  "limpieza/colorantes-y-almidones",
  "limpieza/colorantes-y-almidones/colorantes",
  "limpieza/desechables",
  "limpieza/desechables/bolsas-para-basura",
  "limpieza/desechables/bolsas-para-cocina",
  "limpieza/desechables/palillos-y-pajillas",
  "limpieza/desechables/papel-aluminio-y-adherente",
  "limpieza/desechables/servilletas",
  "limpieza/desechables/toallas-de-cocina",
  "limpieza/desechables/vasos-y-platos",
  "limpieza/detergente",
  "limpieza/detergente/detergente-en-polvo",
  "limpieza/detergente/detergente-liquido",
  "limpieza/jabon-de-lavanderia",
  "limpieza/jabon-de-lavanderia/jabon-de-barra",
  "limpieza/lavaplatos",
  "limpieza/lavaplatos/lavaplatos-en-polvo-y-en-pasta",
  "limpieza/lavaplatos/lavaplatos-liquido",
  "limpieza/limpieza-del-hogar",
  "limpieza/limpieza-del-hogar/cera-para-pisos",
  "limpieza/limpieza-del-hogar/cloro",
  "limpieza/limpieza-del-hogar/cuidado-para-zapatos",
  "limpieza/limpieza-del-hogar/desinfectantes",
  "limpieza/limpieza-del-hogar/destapacanos",
  "limpieza/limpieza-del-hogar/insecticidas-y-trampas",
  "limpieza/limpieza-del-hogar/limpiadores-de-bano",
  "limpieza/limpieza-del-hogar/limpiadores-de-cocina",
  "limpieza/limpieza-del-hogar/limpiadores-multiusos",
  "limpieza/limpieza-del-hogar/toallitas-desinfectantes",
  "limpieza/mascotas",
  "limpieza/mascotas/alimento-humedo-para-gatos",
  "limpieza/mascotas/alimento-humedo-para-perros",
  "limpieza/papel-higienico",
  "limpieza/papel-higienico/empaques-de-18-y-12-rollos",
  "limpieza/papel-higienico/empaques-de-32-y-24-rollos",
  "limpieza/papel-higienico/empaques-de-6-y-4-rollos",
  "limpieza/quitamanchas-para-ropa",
  "limpieza/quitamanchas-para-ropa/quitamanchas-en-polvo",
  "limpieza/quitamanchas-para-ropa/quitamanchas-liquido",
  "limpieza/suavizante",
  "limpieza/suavizante/suavizante-regular",
  "mascota",
  "mascota/accesorios-para-perros",
  "mascota/alimento-humedo-para-gatos",
  "mascota/alimento-humedo-para-perros",
  "mascota/alimento-seco-para-gatos",
  "mascota/alimento-seco-para-perros",
  "mascota/alimento-y-accesorios-otras-mascotas",
  "mascota/arena-y-accesorios-para-gatos",
  "mascota/limpieza-y-cuidado",
  "mascota/premios-y-carnazas",
  "panaderia-y-tortilleria",
  "panaderia-y-tortilleria/comida-y-snacks",
  "panaderia-y-tortilleria/comida-y-snacks/barra-de-ensaladas",
  "panaderia-y-tortilleria/comida-y-snacks/barra-de-postres",
  "panaderia-y-tortilleria/comida-y-snacks/bebidas-preparadas",
  "panaderia-y-tortilleria/comida-y-snacks/fritos-y-rostizados",
  "panaderia-y-tortilleria/comida-y-snacks/guisados",
  "panaderia-y-tortilleria/comida-y-snacks/platillos-preparados",
  "panaderia-y-tortilleria/comida-y-snacks/sandwiches-pizza-y-hot-dog",
  "panaderia-y-tortilleria/comida-y-snacks/sopas-y-guarniciones",
  "panaderia-y-tortilleria/pan-dulce",
  "panaderia-y-tortilleria/pan-dulce/bizcochos",
  "panaderia-y-tortilleria/pan-dulce/empacados",
  "panaderia-y-tortilleria/pan-salado",
  "panaderia-y-tortilleria/pan-salado/bagels",
  "panaderia-y-tortilleria/pan-salado/bocadillos-y-empanadas",
  "panaderia-y-tortilleria/pan-salado/bollos-y-hot-dog",
  "panaderia-y-tortilleria/pan-salado/crutones",
  "panaderia-y-tortilleria/pan-salado/empanizadores",
  "panaderia-y-tortilleria/pan-salado/pan-de-caja",
  "panaderia-y-tortilleria/pan-salado/pan-europeo-y-rustico",
  "panaderia-y-tortilleria/pan-salado/pan-tostado",
  "panaderia-y-tortilleria/reposteria-y-pasteleria",
  "panaderia-y-tortilleria/reposteria-y-pasteleria/pasteles-y-pays",
  "panaderia-y-tortilleria/reposteria-y-pasteleria/roscas-y-panques",
  "panaderia-y-tortilleria/tortilleria",
  "panaderia-y-tortilleria/tortilleria/pan-pita",
  "panaderia-y-tortilleria/tortilleria/tortillas-de-harina",
  "panaderia-y-tortilleria/tortilleria/tortillas-de-maiz",
  "panaderia-y-tortilleria/tortilleria/tostadas"

]


HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept": "application/json",
    "Referer": "https://www.walmart.co.cr/",
    "Origin": "https://www.walmart.co.cr",
    "Accept-Language": "es-CR,es;q=0.9,en;q=0.8",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache"
}

def log(msg):
    print(msg)
    with open("logs/walmart_scraper_simple.log", "a", encoding="utf-8") as f:
        f.write(msg + "\n")

def extraer_categoria(slug):
    productos = []
    pagina = 0
    log(f"\nCategoría: {slug}")
    while True:
        _from = pagina * 50
        _to = _from + 49
        if _to > 25000:
            break

        url = f"{SEARCH_API}/{slug}?_from={_from}&_to={_to}&O=OrderByTopSaleDESC&sc=1"

        try:
            res = requests.get(url, headers=HEADERS, timeout=10)
            if res.status_code != 200:
                log(f" Error HTTP {res.status_code} en {slug} [{_from}-{_to}]")
                break

            data = res.json()
            if not data:
                break

            for p in data:
                try:
                    item = {
                        "nombre": p.get("productName", "").strip(),
                        "sku": str(p.get("productId", "")).strip(),
                        "marca": p.get("brand", "").strip(),
                        "categoria": p.get("categories", [""])[0].strip(),
                        "url": f"{BASE_URL}/{p.get('linkText', '')}/p",
                        "imagen": p.get("items", [{}])[0].get("images", [{}])[0].get("imageUrl", ""),
                        "precio": p.get("items", [{}])[0].get("sellers", [{}])[0].get("commertialOffer", {}).get("Price", 0),
                        "precio_original": p.get("items", [{}])[0].get("sellers", [{}])[0].get("commertialOffer", {}).get("ListPrice", 0),
                        "stock": p.get("items", [{}])[0].get("sellers", [{}])[0].get("commertialOffer", {}).get("AvailableQuantity", 0),
                        "ean": p.get("items", [{}])[0].get("ean", "")
                    }
                    productos.append(item)
                except Exception as e:
                    log(f"  Error en producto: {e}")
                    continue

            pagina += 1
            time.sleep(0.5)
        except Exception as e:
            log(f"  Error consultando productos: {e}")
            break
    return productos

def main():
    log(f"===== INICIO {datetime.now()} =====")
    todos = []
    for cat in CATEGORIAS:
        productos = extraer_categoria(cat)
        todos.extend(productos)

    with open("walmart_productos_simple.json", "w", encoding="utf-8") as f:
        json.dump(todos, f, indent=2, ensure_ascii=False)

    log(f"Total productos extraídos: {len(todos)}")
    log(f"===== FIN {datetime.now()} =====")

if __name__ == "__main__":
    main()
